### ISSUE TITLE
Source code to do the analysis

### ISSUE THREAD

**Issue by richelbilderbeek** [timmassingham/EDIBLE#1]
Hi @timmassingham, 

I was redirected to this GitHub with my question how the analysis was done in:

Goldman, Nick. "Phylogenetic information and experimental design in molecular systematics." Proceedings of the Royal Society of London B: Biological Sciences 265.1407 (1998): 1779-1786.

Sure, I can get EDIBLE to work, but I'd like to see how the pictures are created. 

I could not find these scripts on the GitHub. Did I overlook them?

Cheers, Richel Bilderbeek

```
Re: Request for software used in article
30 May 2017  20:52  7 KB
From: Tracey Andrew
To: Richel Bilderbeek

Dear Richel

Dr Goldman has advised that the information you have requested is available on Github: https://github.com/timmassingham/EDIBLE

Kind regards
Tracey
```

```
On 15/05/2017 13:59, Richel Bilderbeek wrote:
Dear miss Andrew,

I'd like to request the source code used to do the analysis in this article:

Goldman, Nick. "Phylogenetic information and experimental design in molecular systematics." Proceedings of the Royal Society of London B: Biological Sciences 265.1407 (1998): 1779-1786.

Thanks for your help!

Cheers, Richel Bilderbeek
```

**Comment by timmassingham** [comment]
Hello.  

Sorry, EDIBLE a package for doing the numerical computations for experimental design and it is up to the users to visualise the results themselves.  The paper you are referring to was written 20 years ago so I'd suspect that, if there ever was a script to generate the graphs, it is probably no longer in existence.  For what it's worth, it looks like the graph of the main numerical result was produced using Gnuplot and this would consistent with the age of the paper.
